name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # trigger on pushes to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # should be dibinsabu111
          password: ${{ secrets.DOCKER_PASSWORD }}   # Docker Hub access token

      - name: Build Docker image
        run: docker build -t dibinsabu111/actions-docker:${{ github.sha }} .

      - name: Push Docker image
        run: docker push dibinsabu111/actions-docker:${{ github.sha }}
